Repository MALI-Dev/E3SM, pull requests merged in 2022-04, with the labels that each got.

#26 Add SMB mask for bareland
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
Labels: enhancement

#25 Add spatially variable von Mises threshold stress
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: enhancement

#24 Damage threshold with von Mises stress calving or eigencalving
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: enhancement, in progress

#32 Fix restart & decomp errors for ismip6 retreat parameterization
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: bug

#31 Add applied basal mass balance fields
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/analysis_members/mpas_li_global_stats.F
  components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
  components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
Labels: clean up

#27 Distribute unablatedVolumeDynCell among neighboring cells in li_apply_front_ablation_velocity
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: clean up
