Repository MALI-Dev/E3SM, pull requests merged in 2023-08, with the labels that each got.

#84 Disable calving into holes in ice shelf
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: enhancement

#83 update the clock early after adaptive deltat is calculated
  components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration.F
  components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe.F
Labels: bug

#85 Update config_start_time and config_stop_time
  components/mpas-albany-landice/bld/namelist_files/namelist_defaults_mali.xml
  components/mpas-albany-landice/src/Registry.xml
Labels: clean up
