Repository MALI-Dev/E3SM, pull requests merged in 2023-04, with the labels that each got.

#75 Update halos before vonMisesStress extrapolation
  components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
Labels: bug, clean up

#76 LandIce: change stride used in velocity solver interface
  components/mpas-albany-landice/src/mode_forward/Interface_velocity_solver.cpp
Labels: Albany

#74 calculate cell mask during intialization
  components/mpas-albany-landice/src/mode_forward/mpas_li_core.F
Labels: enhancement
