Repository MALI-Dev/E3SM, pull requests merged in 2024-03, with the labels that each got.

#99 Add restart option when the SLM is coupled to MALI
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/mode_forward/mpas_li_bedtopo.F
  components/mpas-albany-landice/src/mode_forward/mpas_li_core.F
Labels: bug, enhancement

#105 Add subglacial hydrology quantities to the regional stats analysis member
  components/mpas-albany-landice/src/Registry.xml
  components/mpas-albany-landice/src/analysis_members/Registry_regional_stats.xml
  components/mpas-albany-landice/src/analysis_members/mpas_li_global_stats.F
  components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
Labels: enhancement

#101 Fix handling of err codes in thermal solver
  components/mpas-albany-landice/src/mode_forward/mpas_li_thermal.F
Labels: bug
